// Mock data for development - will be replaced with Supabase queries

export const mockLeagues = [
  { id: "1", name: "Premier League", slug: "premier-league", sport: "football", country: "England", is_featured: true },
  { id: "2", name: "Champions League", slug: "champions-league", sport: "football", country: "Europe", is_featured: true },
  { id: "3", name: "Serie A", slug: "serie-a", sport: "football", country: "Italy", is_featured: true },
  { id: "4", name: "La Liga", slug: "la-liga", sport: "football", country: "Spain", is_featured: true },
  { id: "5", name: "Bundesliga", slug: "bundesliga", sport: "football", country: "Germany", is_featured: true },
];

export const mockTeams = [
  { id: "1", name: "Manchester City", slug: "manchester-city" },
  { id: "2", name: "Arsenal", slug: "arsenal" },
  { id: "3", name: "Liverpool", slug: "liverpool" },
  { id: "4", name: "Chelsea", slug: "chelsea" },
  { id: "5", name: "Real Madrid", slug: "real-madrid" },
  { id: "6", name: "Barcelona", slug: "barcelona" },
  { id: "7", name: "Bayern Munich", slug: "bayern-munich" },
  { id: "8", name: "Juventus", slug: "juventus" },
  { id: "9", name: "Inter Milan", slug: "inter-milan" },
  { id: "10", name: "Atletico Madrid", slug: "atletico-madrid" },
];

const today = new Date();
const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);

export const mockFixtures = [
  {
    id: "1",
    slug: "manchester-city-vs-arsenal",
    league: mockLeagues[0],
    homeTeam: mockTeams[0],
    awayTeam: mockTeams[1],
    kickoffAt: new Date(today.setHours(15, 0, 0, 0)).toISOString(),
    venue: "Etihad Stadium",
    status: "scheduled",
  },
  {
    id: "2",
    slug: "liverpool-vs-chelsea",
    league: mockLeagues[0],
    homeTeam: mockTeams[2],
    awayTeam: mockTeams[3],
    kickoffAt: new Date(today.setHours(17, 30, 0, 0)).toISOString(),
    venue: "Anfield",
    status: "scheduled",
  },
  {
    id: "3",
    slug: "real-madrid-vs-barcelona",
    league: mockLeagues[3],
    homeTeam: mockTeams[4],
    awayTeam: mockTeams[5],
    kickoffAt: new Date(today.setHours(20, 0, 0, 0)).toISOString(),
    venue: "Santiago Bernabéu",
    status: "scheduled",
  },
  {
    id: "4",
    slug: "bayern-munich-vs-juventus",
    league: mockLeagues[1],
    homeTeam: mockTeams[6],
    awayTeam: mockTeams[7],
    kickoffAt: new Date(today.setHours(21, 0, 0, 0)).toISOString(),
    venue: "Allianz Arena",
    status: "scheduled",
  },
  {
    id: "5",
    slug: "inter-milan-vs-atletico-madrid",
    league: mockLeagues[1],
    homeTeam: mockTeams[8],
    awayTeam: mockTeams[9],
    kickoffAt: new Date(tomorrow.setHours(21, 0, 0, 0)).toISOString(),
    venue: "San Siro",
    status: "scheduled",
  },
  {
    id: "6",
    slug: "arsenal-vs-liverpool",
    league: mockLeagues[0],
    homeTeam: mockTeams[1],
    awayTeam: mockTeams[2],
    kickoffAt: new Date(tomorrow.setHours(16, 30, 0, 0)).toISOString(),
    venue: "Emirates Stadium",
    status: "scheduled",
  },
  {
    id: "7",
    slug: "barcelona-vs-bayern-munich",
    league: mockLeagues[1],
    homeTeam: mockTeams[5],
    awayTeam: mockTeams[6],
    kickoffAt: new Date(tomorrow.setHours(21, 0, 0, 0)).toISOString(),
    venue: "Camp Nou",
    status: "scheduled",
  },
  {
    id: "8",
    slug: "juventus-vs-inter-milan",
    league: mockLeagues[2],
    homeTeam: mockTeams[7],
    awayTeam: mockTeams[8],
    kickoffAt: new Date(tomorrow.setHours(18, 0, 0, 0)).toISOString(),
    venue: "Allianz Stadium",
    status: "scheduled",
  },
];

export const mockBookmakers = [
  { id: "1", name: "Bet365", slug: "bet365", is_featured: true },
  { id: "2", name: "William Hill", slug: "william-hill", is_featured: true },
  { id: "3", name: "Paddy Power", slug: "paddy-power", is_featured: true },
];

export const mockOffers = [
  {
    id: "1",
    title: "Bet £10 Get £30 in Free Bets",
    slug: "bet365-welcome",
    bookmaker: mockBookmakers[0],
    description: "New customers only. Place a qualifying bet of £10 and get £30 in free bets.",
    terms: "18+ T&Cs Apply. New customers only.",
    targetUrl: "https://example.com/bet365",
    is_featured: true,
  },
  {
    id: "2",
    title: "£40 in Free Bets When You Bet £10",
    slug: "william-hill-welcome",
    bookmaker: mockBookmakers[1],
    description: "Get £40 in free bets when you place your first £10 bet.",
    terms: "18+ T&Cs Apply. New customers only.",
    targetUrl: "https://example.com/williamhill",
    is_featured: true,
  },
  {
    id: "3",
    title: "Bet £10 Get £50 in Free Bets",
    slug: "paddy-power-welcome",
    bookmaker: mockBookmakers[2],
    description: "Place a £10 bet on any sport and receive £50 in free bets.",
    terms: "18+ T&Cs Apply. New customers only.",
    targetUrl: "https://example.com/paddypower",
    is_featured: true,
  },
];

export const mockTips = [
  {
    id: "1",
    title: "Champions League Super Mega Accumulator",
    market: "acca",
    fixture: mockFixtures[3],
    selection: "Bayern Munich to Win",
    odds: 1.65,
    stars: 4,
    reasoningShort: "Bayern have dominated at home this season with 8 wins in 9 games.",
    reasoningLong: "Bayern Munich have been in scintillating form at home, winning 8 of their last 9 matches at the Allianz Arena. Juventus have struggled on the road in Europe, losing 3 of their last 5 away fixtures in the Champions League.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Premier League Bet of the Day",
    market: "bet-of-the-day",
    fixture: mockFixtures[0],
    selection: "Manchester City to Win & Over 2.5 Goals",
    odds: 1.85,
    stars: 5,
    reasoningShort: "City are unstoppable at home and Arsenal have conceded in 7 straight away games.",
    reasoningLong: "Manchester City have won their last 12 home Premier League matches, scoring an average of 3.2 goals per game. Arsenal have been leaky on the road, conceding in 7 consecutive away fixtures.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Both Teams to Score - El Clasico",
    market: "btts",
    fixture: mockFixtures[2],
    selection: "Both Teams to Score - Yes",
    odds: 1.72,
    stars: 4,
    reasoningShort: "El Clasico rarely disappoints with goals from both sides.",
    reasoningLong: "The last 8 El Clasico matches have seen both teams score. Real Madrid's attacking prowess combined with Barcelona's recent defensive vulnerabilities make BTTS a strong selection.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Correct Score - Liverpool vs Chelsea",
    market: "correct-score",
    fixture: mockFixtures[1],
    selection: "Liverpool 2-1",
    odds: 7.50,
    stars: 3,
    reasoningShort: "Anfield is a fortress and this scoreline has occurred in 3 of their last 5 meetings.",
    reasoningLong: "Liverpool have been dominant at Anfield, and this exact scoreline has occurred in 3 of the last 5 meetings between these sides at this venue. A high-value pick for those looking for bigger returns.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Over 2.5 Goals - Serie A Derby",
    market: "over-under",
    fixture: mockFixtures[7],
    selection: "Over 2.5 Goals",
    odds: 1.80,
    stars: 4,
    reasoningShort: "The Derby d'Italia always delivers entertainment.",
    reasoningLong: "The last 6 meetings between Juventus and Inter Milan have produced over 2.5 goals. Both teams are in good attacking form and have porous defences when facing top opposition.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Double Chance - Safe Pick",
    market: "double-chance",
    fixture: mockFixtures[4],
    selection: "Inter Milan or Draw",
    odds: 1.45,
    stars: 5,
    reasoningShort: "Inter are unbeaten at home this season in all competitions.",
    reasoningLong: "Inter Milan haven't lost at the San Siro this season. Atletico Madrid are strong defensively but struggle to score away from home, making a draw or Inter win highly likely.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "6-Fold BTTS Accumulator",
    market: "acca",
    fixture: mockFixtures[0],
    selection: "BTTS in 6 matches - 28/1",
    odds: 29.00,
    stars: 3,
    reasoningShort: "High-value accumulator covering today's biggest fixtures.",
    reasoningLong: "This accumulator covers 6 carefully selected matches where both teams scoring is highly probable based on recent form and head-to-head statistics.",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Weekend Mega Acca",
    market: "acca",
    fixture: mockFixtures[5],
    selection: "5-Fold Winner Acca - 18/1",
    odds: 19.00,
    stars: 3,
    reasoningShort: "Five favorites to win across Europe's top leagues.",
    reasoningLong: "A carefully constructed accumulator featuring five of the most likely winners from this weekend's fixtures across the Premier League, La Liga, and Serie A.",
    publishedAt: new Date().toISOString(),
  },
];

export const mockPreviews = [
  {
    id: "1",
    title: "Manchester City vs Arsenal Predictions & Betting Tips",
    slug: "manchester-city-vs-arsenal",
    fixture: mockFixtures[0],
    intro: "A massive clash at the Etihad as Manchester City host title rivals Arsenal in what could be a defining match for the Premier League season.",
    tips: [mockTips[1]],
    publishedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Real Madrid vs Barcelona El Clasico Preview",
    slug: "real-madrid-vs-barcelona",
    fixture: mockFixtures[2],
    intro: "The biggest match in club football returns as Real Madrid welcome Barcelona to the Bernabéu for another chapter in this historic rivalry.",
    tips: [mockTips[2]],
    publishedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Bayern Munich vs Juventus Champions League Preview",
    slug: "bayern-munich-vs-juventus",
    fixture: mockFixtures[3],
    intro: "Two European giants clash in a crucial Champions League encounter that could determine who tops the group.",
    tips: [mockTips[0]],
    publishedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Juventus vs Inter Milan Derby d'Italia Preview",
    slug: "juventus-vs-inter-milan",
    fixture: mockFixtures[7],
    intro: "Italy's biggest rivalry takes center stage as Juventus and Inter Milan meet in the Derby d'Italia.",
    tips: [mockTips[4]],
    publishedAt: new Date().toISOString(),
  },
];

export const mockArticles = [
  {
    id: "1",
    title: "Champions League 380/1 Accumulator for Wednesday's Action",
    slug: "champions-league-acca-wednesday",
    article_type: "news",
    excerpt: "Our experts have put together an incredible 380/1 accumulator covering all of Wednesday's Champions League fixtures.",
    body: "Full article content here...",
    is_featured: true,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Premier League Weekend Preview: All the Best Bets",
    slug: "premier-league-weekend-preview",
    article_type: "news",
    excerpt: "Everything you need to know about this weekend's Premier League action, including our top picks.",
    body: "Full article content here...",
    is_featured: true,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "28/1 BTTS Six-Fold Accumulator for This Week",
    slug: "btts-six-fold-acca",
    article_type: "news",
    excerpt: "A high-value BTTS accumulator covering matches across Europe's top leagues.",
    body: "Full article content here...",
    is_featured: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "Betting Academy: Complete Guide to Football Betting",
    slug: "betting-academy-guide",
    article_type: "academy",
    excerpt: "Learn everything you need to know about football betting with our comprehensive guide.",
    body: "Full article content here...",
    is_featured: false,
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    title: "Experts' Best Bets: Top 5 Tipsters Pick Their Winners",
    slug: "experts-best-bets",
    article_type: "news",
    excerpt: "Five of our top tipsters reveal their best selections for the upcoming fixtures.",
    body: "Full article content here...",
    is_featured: false,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    title: "How to Build Winning Accumulators",
    slug: "how-to-build-accas",
    article_type: "academy",
    excerpt: "Master the art of accumulator betting with our expert tips and strategies.",
    body: "Full article content here...",
    is_featured: false,
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
